export const products = [
  {
    id: 1,
    name: "Katter",
    price: 15,
    image: require("./assets/product-1.jpg"),
  },
  {
    id: 2,
    name: "Vase",
    price: 77,
    image: require("./assets/product-2.jpg"),
  },
  {
    id: 3,
    name: "Artificial potted plant",
    price: 40.0,
    image: require("./assets/product-3.jpg"),
    classname: "decoration",
  },
  {
    id: 4,
    name: "Dark Green Jug",
    price: 17.1,
    image: require("./assets/product-4.jpg"),
    classname: "accessory",
  },
  {
    id: 5,
    name: "Drinking Glasses",
    price: 21.0,
    image: require("./assets/product-5.jpg"),
    classname: "accessory",
  },
  {
    id: 6,
    name: "Helen Chair",
    price: 919.11,
    image: require("./assets/product-6.jpg"),
    classname: "furniture",
  },
  {
    id: 7,
    name: "High Quality Glass Bottle",
    price: 30.1,
    image: require("./assets/product-7.jpg"),
    classname: "accessory",
  },
  {
    id: 8,
    name: "Living Room & Bedroom Lights",
    price: 45.0,
    image: require("./assets/product-8.jpg"),
    classname: "accessory",
  },
  {
    id: 9,
    name: "Nancy Chair",
    price: 90.0,
    image: require("./assets/product-9.jpg"),
    classname: "furniture",
  },
  {
    id: 10,
    name: " Simple Chair",
    price: 40.0,
    image: require("./assets/product-10.jpg"),
    classname: "furniture",
  },
  {
    id: 11,
    name: "Smooth Disk",
    price: 46.0,
    image: require("./assets/product-11.jpg"),
    classname: "decoration",
  },
  {
    id: 12,
    name: "Table Black",
    price: 67.0,
    image: require("./assets/product-12.jpg"),
    classname: "furniture",
  },
  {
    id: 13,
    name: "Table Wood Pine",
    price: 50.0,
    image: require("./assets/product-13.jpg"),
    classname: "furniture",
  },
  {
    id: 14,
    name: "Teapot with black tea",
    price: 25.0,
    image: require("./assets/product-14.jpg"),
    classname: "accessory",
  },
  {
    id: 15,
    name: "Unique Decoration",
    price: 15.0,
    image: require("./assets/product-15.jpg"),
    classname: "decoration",
  },
  {
    id: 16,
    name: "Vase Of Flowers",
    price: 77.0,
    image: require("./assets/product-16.jpg"),
    classname: "decoration",
  },
  {
    id: 17,
    name: "Wood Eggs",
    price: 19.0,
    image: require("./assets/product-17.jpg"),
    classname: "decoration",
  },
  {
    id: 18,
    name: "Wooden Box",
    price: 27.0,
    image: require("./assets/product-18.jpg"),
    classname: "decoration",
  },
  {
    id: 19,
    name: "Wooden Cups",
    price: 29.0,
    image: require("./assets/product-19.jpg"),
    classname: "accessory",
  },
];
